<?php
$config = array (
  'admin_directory' => 'admin',
  'directory' => '',
  'db_driver' => 'auto',
	'db_host' => 'localhost',
	'db_base' => 'siverski_gtn',
	'db_user' => 'siverski_gtn',
	'db_pass' => 'lizza83', 
  'db_prefix' => '',
  'datetime_format' => 'd-m-Y H:i',
  'date_format' => 'd-m-y',
  'time_format' => 'H:i',
  'img_max_size' => '1024',
  'watermark' => '/public/images/thumbs/200x200/noimg.jpg',
  'watermark_active' => '0',
  'watermark_type' => 'top_left',
  'admin_template' => 'default',
  'lang' => 'ru',
  'admin_lang' => 'ru',
  'debug' => '1',
  'debug_info' => '1',
  'editor' => 'ckeditor',
  'editor_active' => '1',
  'filemanager' => 'elfinder',
  'filemanager_active' => 1,
  'link_end' => '/',

);